name: "BiB VPN"

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  HiN-VPN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          
      - name: Execute PHP script
        run: |
          php base.php
          git config --global user.name "NET Sentinel Bot"
          git config --global user.email "224584266+NetSentinel-Bot@users.noreply.github.com"
          git config credential.helper store
          git add -A
          git commit -m "Auto: Update configurations at:  $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
